name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Interactive shell for when things go south
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: cache installation
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
    # Push to server
    - name: rsync and ssh
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST_UBCO }}
        REMOTE_USER: ${{ secrets.REMOTE_USER_UBCO }}
        REMOTE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_DIR: ${{ secrets.REMOTE_TARGET_UBCO }}
        LOCAL_DIR: "_build/html/"
        COURSE_NAME: "data530"
        TERM: "2021_WT1"
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
#       run: |
#         mkdir ~/.ssh
#         echo "$REMOTE_KEY" > ~/.ssh/id_rsa
#         ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
#         chmod 600 ~/.ssh/id_rsa
#         pwd
#         ls -la
#         rsync -avzr --delete $LOCAL_DIR $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/courses/$TERM/$COURSE_NAME
